jkh/debts/urls.py
from django.urls import path

from .views import DebtPayment


app_name = 'debts'

urlpatterns = [
    path('<str:type>/payment/', DebtPayment.as_view(), name='debt_payment'),
]

jkh/jkh/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .views import HomeView, AdviceView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),
    path('advice/', AdviceView.as_view(), name='advice'),
    path('accounts/', include('users.urls'), name='accounts'),
    path('debts/', include('debts.urls'), name='debts'),
    path("pages/", include("django.contrib.flatpages.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jkh/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import SignUp, PasswordChangeView, edit_profile


app_name = 'users'

urlpatterns = [
    path("login/", LoginView.as_view(
        template_name="users/login.html",
        redirect_authenticated_user=True
    ), name="login"),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),

    path('password/change/',
         PasswordChangeView.as_view(),
         name='profile_change_password'),

    path('profile/change/', edit_profile, name='profile_change'),
]

jkh/jkh/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "main.html"


class AdviceView(TemplateView):
    template_name = "advice.html"

jkh/jkh/templates/advice.html
{% extends 'shell.html' %}
{% load static %}

{% block content %}
    <div class="main__component">
        <a href="{% url 'home' %}"><img src="{% static 'img/back.svg' %}" alt="back" class="back"></a>
        <div class="left__main">
            <div class="left__text">Советы</div>
            <div class="advice__btns">
                <div class="advice__btn">
                    <a href="/advices/benefits/">
                        <button>
                            <div>Льготы участникам
                                ВОВ</div>
                        </button>
                    </a>
                    <a href="/advices/benefits/">
                        <button>
                            <div>Льготы участникам
                                ВОВ</div>
                        </button>
                    </a>
                </div>
                <div class="advice__btn">
                    <a href="/advices/benefits/">
                        <button>
                            <div>Льготы участникам
                                ВОВ</div>
                        </button>
                    </a>
                    <a href="/advices/benefits/">
                        <button>
                            <div>Льготы участникам
                                ВОВ</div>
                        </button>
                    </a>
                </div>
            </div>
        </div>
        <div class="right__payDetal">
            <div class="buttons__payDetal">
                <button><img src="{% static 'img/microphone.svg' %}" alt="microphone">Голосовой помощник</button>
                <button><img src="{% static 'img/adjust.svg' %}" alt="">Контрастный интерфейс</button>
                <button><img src="{% static 'img/search.svg' %}" alt="">Лупа</button>
            </div>
        </div>
    </div>
{% endblock %}

jkh/jkh/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Document{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" xmlns="http://www.w3.org/1999/html">
    {% block head_extra %}{% endblock %}
</head>

<body>
{% block body %}{% endblock %}
{% block body_extra %}{% endblock %}
</body>
</html>

jkh/jkh/templates/main.html
{% extends 'shell.html' %}
{% load static %}

{% block content %}
    <div class="main__component">
        <div class="left__main">
            <div class="left__text">Оплата услуг</div>
            <div class="buttons__pay">
                <a href="{% url 'debts:debt_payment' 'gas' %}">Оплатить газ<img src="{% static 'img/fire.svg' %}" alt="fire"></a>
                <a href="{% url 'debts:debt_payment' 'electricity' %}">Оплатить свет<img src="{% static 'img/bulb.svg' %}" alt="bulb"></a>
                <a href="{% url 'debts:debt_payment' 'water' %}">Оплатить воду<img src="{% static 'img/water.svg' %}" alt="water"></a>
            </div>
        </div>
        <div class="right">
            <div class="login__right_mix">
                <div class="links">
                    <a href="{% url 'users:profile_change' %}">Личный кабинет</a>
                    <a href="{% url 'advice' %}">Советы</a>
                </div>
                <div class="right__btns">
                    <button class="microphone"><img src="{% static 'img/microphone.svg' %} " alt="microphone">Голосовой
                        помощник</button>
                    <button class="adjust"><img src="{% static 'img/adjust.svg' %} " alt="">Контрастный интерфейс</button>
                    <button class="search"><img src="{% static 'img/search.svg' %} " alt="">Лупа</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

jkh/jkh/templates/shell.html
{% extends "base.html" %}

{% block body %}
    <header class="header">
        <a href="{% url 'home' %}" class="header__text">Оплата ЖКХ</a>
        <form action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="header__logout">Выйти</button>
        </form>
    </header>
    {% block content %}
    {% endblock %}
{% endblock %}