jkh/jkh/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .views import HomeView, AdviceView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),
    path('advice/', AdviceView.as_view(), name='advice'),
    path('accounts/', include('users.urls'), name='accounts'),
    path('debts/', include('debts.urls'), name='debts'),
    path("pages/", include("django.contrib.flatpages.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jkh/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import SignUp, PasswordChangeView, edit_profile


app_name = 'users'

urlpatterns = [
    path("login/", LoginView.as_view(
        template_name="users/login.html",
        redirect_authenticated_user=True
    ), name="login"),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),

    path('password/change/',
         PasswordChangeView.as_view(),
         name='profile_change_password'),

    path('profile/change/', edit_profile, name='profile_change'),
]

jkh/users/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_('The Email must be sent'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField("Имя", max_length=150)
    last_name = models.CharField("Фамилия", max_length=150)
    patronymic = models.CharField("Отчество", max_length=150)
    email = models.EmailField("Email", unique=True)

    gas_account = models.CharField(
        "Лицевой счет по газоснабжению",
        max_length=12,
        unique=True,
        null=True,
        blank=True
    )
    electricity_account = models.CharField(
        "Лицевой счет по электроснабжению",
        max_length=12,
        unique=True,
        null=True,
        blank=True
    )
    water_account = models.CharField(
        "Лицевой счет по водоснабжению",
        max_length=12,
        unique=True,
        null=True,
        blank=True
    )

    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        full_name = "%s %s %s" % (self.patronymic, self.first_name, self.last_name)
        return full_name.strip()

    def get_initials(self):
        full_name = "%s %s. %s." % (self.patronymic, self.first_name[0], self.last_name[0])
        return full_name.strip()

    def get_short_name(self):
        short_name = "%s %s" % (self.patronymic, self.first_name)
        return short_name.strip()

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

jkh/users/forms.py
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm, UserChangeForm as BaseUserChangeForm
from django.contrib.auth import get_user_model

User = get_user_model()


class UserCreationForm(BaseUserCreationForm):
    class Meta(BaseUserCreationForm.Meta):
        model = User
        fields = ('last_name', 'first_name', 'patronymic', 'email')


class UserChangeForm(BaseUserChangeForm):
    class Meta:
        model = User
        fields = ('last_name', 'first_name', 'patronymic', 'email', 'gas_account',
                  'electricity_account', 'water_account')
        exclude = ('password',)


# class UserUpdateForm(forms.ModelForm):
#     username = forms.CharField(
#         validators=[UnicodeUsernameValidator()],
#         label='Имя пользователя',
#         widget=MaterialTextInput(
#             help_text='Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.',
#             persistent_help_text=True,
#            ),
#        )
#
#     class Meta:
#         model = User
#         fields = ('username',)

jkh/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView as BasePasswordChangeView
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView, FormView
from django.urls import reverse_lazy

from .forms import UserCreationForm, UserChangeForm

User = get_user_model()


class SignUp(CreateView):
    form_class = UserCreationForm
    # После успешной регистрации перенаправляем пользователя в личный кабинет.
    success_url = reverse_lazy('users:profile_change')
    template_name = 'users/signup.html'


class PasswordChangeView(BasePasswordChangeView):
    success_url = reverse_lazy('users:profile')
    form_class = SetPasswordForm
    success_message = 'Пароль успешно изменен'


# TODO: сделать адекватную вьюшку и выбрать одно из трех ниже (cbv или функия)
@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = UserChangeForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Данные успешно обновлены')
            return render(request, 'users/personal_account.html', context={'form': form})
        return render(request, 'users/personal_account.html', {'form': form})
    else:
        form = UserChangeForm(instance=request.user)
        context = {'form': form}
        return render(request, 'users/personal_account.html', context)


class UserChangeView(LoginRequiredMixin, FormView):
    template_name = 'users/personal_account.html'
    model = User
    form_class = UserChangeForm
    success_url = 'Данные успешно обновлены'

    def get(self, request, *args, **kwargs):
        return super(UserChangeView, self).get(request, *args, **kwargs)


class ProfileDetailView(LoginRequiredMixin, TemplateView):
    template_name = 'users/personal_account.html'

jkh/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="login__component component">
        <div class="left">
            <div class="login__contentLeft">
                <div class="left__text">Вход в систему</div>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="login__input">
                        <label><input type="text" name="username" placeholder="E-mail" class="input" required></label>
                        <input type="password" name="password" placeholder="Пароль" class="input" required>
                    </div>
                    {% for error in form.errors.values %}
                        <ul>
                            <li>{{ error }}</li>
                        </ul>
                    {% endfor %}
                    <button class="left__btn" type="submit">Войти</button>
                    <div class="left__password">Забыли пароль? <a href="#">Восстановить</a></div>
                    <div class="left__password">
                        <a href="{% url 'users:signup' %}">Зарегистрироваться</a>
                    </div>
                </form>
            </div>
        </div>
        <div class="right">
            <div class="login__right_mix">
                <h1 class="right__text"><span>Оплата</span><span>ЖКХ</span></h1>
                <div class="right__btns">
                    <button class="microphone"><img src="{% static 'img/microphone.svg' %}" alt="microphone">Голосовой
                        помощник</button>
                    <button class="adjust"><img src="{% static 'img/adjust.svg' %}" alt="">Контрастный интерфейс</button>
                    <button class="search"><img src="{% static 'img/search.svg' %}" alt="">Лупа</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

jkh/users/templates/users/personal_account.html
{% extends 'shell.html' %}

{% load static %}

{% block content %}
    <div class="main__component">
        <a href="{% url 'home' %}"><img src="{% static 'img/back.svg' %}" alt="back" class="back"></a>
        <div class="left__personalAccount">
            <div class="left__text">Личный кабинет</div>
            <form method="post" action="">
                {% csrf_token %}
                <div class="login__input">
                    <input type="text" name="last_name" placeholder="Фамилия" value="{{ form.last_name.value|default_if_none:'' }}" class="input">
                    <input type="text" name="first_name" placeholder="Имя" value="{{ form.first_name.value|default_if_none:'' }}" class="input">
                    <input type="text" name="patronymic" placeholder="Отчество" value="{{ form.patronymic.value|default_if_none:'' }}" class="input">
                    <input type="text" name="email" placeholder="E-mail" value="{{ form.email.value|default_if_none:'' }}" class="input">
                    <input type="text" name="gas_account" placeholder="Лицевой счёт по газоснобжению" value="{{ form.gas_account.value|default_if_none:'' }}" class="input">
                    <input type="text" name="electricity_account" placeholder="Лицевой счёт по электроснобжению" value="{{ form.electricity_account.value|default_if_none:'' }}" class="input">
                    <input type="text" name="water_account" placeholder="Лицевой счёт по водоснобжению" value="{{ form.water_account.value|default_if_none:'' }}" class="input">
                    {% for error in form.errors.values %}
                        <ul>
                            <li>{{ error }}</li>
                        </ul>
                    {% endfor %}
                </div>
                <button class="left__btn" type="submit">Сохранить</button>
            </form>
            <div class="left__text">Смена пароля</div>
            <form action="{% url 'users:profile_change_password' %}" method="post">
                {% csrf_token %}
                <div class="login__input">
                    <input type="password" name="new_password1" placeholder="Новый пароль" class="input">
                    <input type="password" name="new_password2" placeholder="Повторите пароль" class="input">
                    {% for error in form.errors.values %}
                        <ul>
                            <li>{{ error }}</li>
                        </ul>
                    {% endfor %}
                </div>
                <button class="left__btn" type="submit">Сохранить</button>
            </form>
        </div>
        <div class="right__payDetal">
            <div class="buttons__payDetal">
                <button><img src="{% static 'img/microphone.svg' %}" alt="microphone">Голосовой помощник</button>
                <button><img src="{% static 'img/adjust.svg' %}" alt="">Контрастный интерфейс</button>
                <button><img src="{% static 'img/search.svg' %}" alt="">Лупа</button>
            </div>
        </div>
    </div>
{% endblock %}

jkh/users/templates/users/signup.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="registration__component component">
        <div class="left">
            <div class="left__text">Регистрация</div>
            <form method="post" action="">
                {% csrf_token %}
                <div class="login__input">
                    <input type="text" name="last_name" placeholder="Фамилия" class="input">
                    <input type="text" name="first_name" placeholder="Имя" class="input">
                    <input type="text" name="patronymic" placeholder="Отчество" class="input">
                    <input type="text" name="email" placeholder="E-mail" class="input">
                    <input type="password" name="password1" placeholder="Пароль" class="input">
                    <input type="password" name="password2" placeholder="Повторите пароль" class="input">
                    {% for error in form.errors.values %}
                        <ul>
                            <li>{{ error }}</li>
                        </ul>
                    {% endfor %}
                </div>
                <button class="left__btn" type="submit">Зарегистрироваться</button>
                <div class="left__password">Есть аккаунт? <a href="{% url 'users:login' %}">Войти</a></div>
            </form>
        </div>
        <div class="right">
            <div class="login__right_mix">
                <h1 class="right__text"><span>Оплата</span><span>ЖКХ</span></h1>
                <div class="right__btns">
                    <button class="microphone"><img src="{% static 'img/microphone.svg' %}" alt="microphone">Голосовой
                        помощник</button>
                    <button class="adjust"><img src="{% static 'img/adjust.svg' %}" alt="">Контрастный интерфейс</button>
                    <button class="search"><img src="{% static 'img/search.svg' %}" alt="">Лупа</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}